### ISSUE TITLE
MS1 analysis with .mgf files

### ISSUE THREAD

**Issue by justinjjvanderhooft** [sdrogers/ms2ldaviz#105]
User request (see below)

Add option to perform MS1 analysis using .mgf files.

-----

I'm using MS2LDA to explore the Euphorbia dataset and support putative structure annotation and it's been really great so far! There is great documentation on the website, which makes it really straightforward to use and putative annotation can also be greatly aided by the Mass2Motifs.

To take it a step further, I'd also like to add an MS1 differential expression analysis. However, when creating a new experiment, I'm only given the option to add an MS1 file, if I choose an MS2 file in .mzML format, and not .mgf.

Is it somehow possible to add an MS1 file to an MS2 file in .mgf format?

**Comment by sdrogers** [comment]
Hi all,
Added Frank as he is the MS1 guru.
Frank: this should be easy I think?
Justin: do you think they would be willing to provide an example .mgf file and an example ms1 file? That would make things much easier. Not sure if there is RT info in the .mgf file? It can work either way.

**Comment by justinjjvanderhooft** [comment]
Example files might come!

She described:  For the networking besides the RT and m/z info, each feature additionally has an ID, which can be used for matching MS1 data and MS2 data in the .mgf file

**Comment by sdrogers** [comment]
Ah, that would make things very easy, and is something we could insist upon for MGF<->MS1 matching?
--
Dr. Simon Rogers
simon.d.rogers@gmail.com

**Comment by justinjjvanderhooft** [comment]
Probably not I would say - I don't think the .mgf format is that well standardized - a bit like the .mzML format....

**Comment by sdrogers** [comment]
But we can insist on whatever we like - it will be hard to detect whether the IDs exist. Given that this is a single request so far, we should insist on IDs (for the matching, not for .mgf in general) and then consider making things more flexible if we get requests...

**Comment by justinjjvanderhooft** [comment]
sure!

**Comment by justinjjvanderhooft** [comment]
Example files are here: https://www.dropbox.com/sh/ok41yyb7fr5g7pu/AAAIGMg2-D3Q0FxzVMU7dHhCa?dl=0

Comments Madeleine: Attached an example .mgf file with corresponding MS1 table (which I prepared according to the description on ms2lda.org). In the .mgf file, FEATURE_ID matches the column FeatureID in the MS1 table. RT and m/z are also given in both files.

**Comment by sdrogers** [comment]
Perfect…Frank — let me know what you think...
--
Dr. Simon Rogers
simon.d.rogers@gmail.com

**Comment by justinjjvanderhooft** [comment]
Alternatively, we could check if RT and m/z info is present in both MS1 file and the MGF file, i.e.:

FEATURE_ID=1864
PEPMASS=250.085473082
RTINSECONDS=644.316

FeatureID | mass | RT
-- | -- | --
3100 | 476.404 | 308.16

**Comment by sdrogers** [comment]
SO, check for an ‘ID’ field and if none exists, check for ms/rt matches and take the closest within some tolerance (I guess they might be exact matches, but that will work — exact ones will always be the closest ones)
--
Dr. Simon Rogers
simon.d.rogers@gmail.com

**Comment by justinjjvanderhooft** [comment]
Yep - indeed!

**Comment by ymcdull** [comment]
will have a look. I guess it is easy to fix, and also maybe the same issue should be fixed for .msp input format.

**Comment by sdrogers** [comment]
yes — a standard fix would be good...
--
Dr. Simon Rogers
simon.d.rogers@gmail.com

**Comment by ymcdull** [comment]
Hi Simon,
The original code is a bit messy,  will refactor some (like processing peaklists) into “Loader” class, and LoadMZML, LoadMPS, LoadMGF will inherit the “Loader” class.

The ms1 analysis for mzml files is to “check for ms/rt matches and take the closest within some tolerance”. I guess this is same for msp and mgf? (no need to check “ID” filed)

One minor question: for msp & mgf format files, is the default setting “min_ms2_intensity” of 5000.0 a little high?

**Comment by justinjjvanderhooft** [comment]
Not sure if this works from gmail, but quick reply on the min. MS2 int.:

Yeah - minimum intensity of 5000 is default for Q-Exactive machines - most
other machines need lower thresholds of about 100 or sometimes even lower.
In theory, folks should look at their files and decide the threshold -
perhaps we could make three or four settings for different mass specs or so.

**Comment by ymcdull** [comment]
Thanks Justin. 

And one potential problem is: some “retention time” in msp files are missing, that will lead to a problem in “rt matching”. If that happens, I think it is better to just compare m/z matches? Agree?

Another thing to double check: 
this Euphorbia mgf file has rt in seconds (RTINSECONDS), but in some msp files like RIKEN, the values of “RETENTIONTIME” is quite small, I guess they are in minutes? Will they always be minutes or uncertain in msp?

**Comment by sdrogers** [comment]
They will vary, unfortunately.
But as long as we say clearly what we expect, then people can't complain.

--
Dr. Simon Rogers
Senior Lecturer, School of Computing Science
University of Glasgow
simon.rogers@glasgow.ac.uk
www.dcs.gla.ac.uk/~srogers

**Comment by justinjjvanderhooft** [comment]
Frank - I know - mgf and msp files are also variable in their exact formats I am afraid. As Simon indicates, we should make clear what the code expects.

As for the matching: it will OR on both RT and m/z OR on identifier. Just a m/z value will get us into trouble when multiple isomers appear etc. So if RT info is missing, we cannot do the matching....
Hope that is clear!

**Comment by justinjjvanderhooft** [comment]
ps I would say let's take RT in seconds for now - as that is the SI unit....

**Comment by sdrogers** [comment]
- I suggest we first check for an identifier. If this exists, we match on that. If not, we match on m/z and rt. I think this is what Justin is suggesting too.
- RT: unfortunately, the files won't have units in them. So, we just have to take what's there. We specify our tolerance in seconds. As long as we're clear that we're expecting seconds, it's the users' problem if they provide things in minutes. It would still work as long as both of their files are in minutes, but they'd probably need to change the threshold.
- min intensity: I agree with Justin but not sure about multiple settings (perhaps just some text giving some recommended values for different equipment...maybe that's what you mean? Could you provide some rough figures?). I think users have to take some responsibility for this. It's much better for a user to have it to high and then have to run the analysis again than for us to end up with a database full up of noisey fragments!
- Frank: for mzml you're right, there will never be an ID. The ID is just an mgf and maybe msp thing.

**Comment by justinjjvanderhooft** [comment]
I agree Simon!

And yes - rough figures would be 5000 for Thermo instruments and 100 for all others [for MS2 min intensity]. The MS1 min intensity is really dependent on the data acquisition settings....

**Comment by ymcdull** [comment]
Hi Simon,
I have made pull requests in ms2ldaviz repo & lda repo for this issue. I have tested on my machine, can you have a look and test when you have time?

- identifier: Current code will check the "FeatureID" in mgf file and peaklist file. Code will detect "featureid" column in peaklist file before "mz" column, and will detect "featureid" or "feature_id" in mgf files (both case-insensitive). If feature id exists, match on it. If not, match on m/z and rt as before.
- RT: leave it as "seconds" in code
- min_ms2_intensity:  I have tried a small value, which make DB writing extremely slow. So here I still leave the default value as 5000.
- Code structure: refactored the parent class *Loader*. Currently, *load_spectra* functions are still quite long, may refactor later when having time.
