### ISSUE TITLE
User Feature Request: csv export of all documents with associated Mass2Motifs (thresholded)

### ISSUE THREAD

**Issue by justinjjvanderhooft** [sdrogers/ms2ldaviz#109]
"I wondered if there is a way to export a .csv table on MS2LDA of all documents with matching motifs (similar to what you can download when clicking on "Show fragmentation spectra" and download .csv for "Associated Mass2Motifs" but not individually for each document (feature) but for all features together). If I would have access to this data as .csv or similar it would be relatively straight forward for me to extract e.g. matching motifs per network cluster and we could check how much motifs and network clusters match in my dataset."

Perhaps we could add an export button in the summary page allowing that. It could request to put thresholds on the probability and/or overlap scores or we could simply use them from the experimental settings page.

**Comment by ymcdull** [comment]
Ok, will do, thanks.

**Comment by ymcdull** [comment]
Hi, justin.
I wanna double check with you that “Show Fragmentation Spectra” and “Show Mass2Motifs” parts are exactly identical to the ones in “Summary Page”? Maybe just hide these two entries? What do you think?

Frank

**Comment by justinjjvanderhooft** [comment]
Hi Frank,

Let's leave them for now. This could be subject for debate if we have a general MS2LDA website meeting or something like that. I think the summary page was meant to kind of 'summarize' the essential information of the other tabs.

Cheers Justin

**Comment by ymcdull** [comment]
Thanks, Justin. 

Have a look at http://52.51.126.142:8000
And please remind me if I missed anything.

Currently I put this part in summary page, if you prefer, I can move it to the main page in each experiment.

It will get “doc - motif” matching based on existing threshold settings: if doc_m2m_prob_threshold and doc_m2m_overlap_threshold have been set by user then apply thoes thresholds. If not, then use global initial settings: doc_m2m_prob_threshold (0.05) and doc_m2m_overlap_threshold (0.0).

Thanks.
Frank

**Comment by justinjjvanderhooft** [comment]
Hi Frank,

Great stuff! I could download the csv okay.

Could we add the parent mass and (if available) retention time info to that Table? That will allow users to match the documents to other analyses. With just the document name (which could be 'document1') that will be a pretty daunting task....

Thanks Justin

**Comment by ymcdull** [comment]
Updated. How about now？

**Comment by justinjjvanderhooft** [comment]
Looks good to me! :-)

**Comment by justinjjvanderhooft** [comment]
Thanks mate!
