### ISSUE TITLE
User registration: add button 'add example experiments' to a new user

### ISSUE THREAD

**Issue by justinjjvanderhooft** [sdrogers/ms2ldaviz#111]
Upon registration, a button to add the following 6 example experiments (5 with view, one with edit permissions to show the difference to the user) to a new user would speed up the registration process.

![image](https://user-images.githubusercontent.com/2318072/31545295-fe00b2b4-b01e-11e7-9a24-a6a01dba6058.png)

**Comment by joewandy** [comment]
Done in a script.
