### ISSUE TITLE
PLAGE motifs are too big!

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/ms2ldaviz#115]
![screen shot 2017-11-21 at 21 05 51](https://user-images.githubusercontent.com/611683/33096688-db8a8f66-ceff-11e7-933a-4fc2a2674cf3.png)
Can we restrict the size of motif nodes, or make the molecules move further away? Impossible to hover over the nodes (see screenshot)?

**Comment by ymcdull** [comment]
will try

**Comment by ymcdull** [comment]
Hi Simon,
change the parameter "charge" in d3 can move molecules further away, but I guess here is a better solution:
always put circles(motifs) under squares (molecules), then we will not have hover issues.
like this:
<img width="567" alt="tmp1" src="https://user-images.githubusercontent.com/1074351/33173099-ac6850a0-d04a-11e7-9edd-b09388e4ae57.png">

What do you think?

**Comment by justinjjvanderhooft** [comment]
It is a working solution I would say....though it depends on the colour (differences) between circles and molecules. In this view it is quite obvious, in the PLAGE view it isn't always that obvious....
