### ISSUE TITLE
Insert original ID column of uploaded MS1 file into exported document-csv files

### ISSUE THREAD

**Issue by justinjjvanderhooft** [sdrogers/ms2ldaviz#117]
Could we ensure that all the columns before mass and RT in an uploaded MS1 peak list csv file are copied into document-csv files exported (i.e., the csv file that contains information on the associated motifs and their probabilities and overlap scores). That would facilitate downstream data handling as those (ID) columns often contain unique identifiers. Now, the document IDs usually become mz_RT concatenations, which is very handy for the ms2ldaviz (as it is telling you the mass and RT of the parent mass directly) but not so much if you want to link the documents back to other (meta)-data.

**Comment by ymcdull** [comment]
Current code just ignored all the columns before "mass", so we can not recover that info from existing experiments. 
But we may modify code to store all the columns before "mass" column, and put it into document-csv file in future experiments.

**Comment by justinjjvanderhooft** [comment]
That would be very neat Frank! 🙂

**Comment by ymcdull** [comment]
Hi Justin,

How about this:
<img width="1013" alt="2017-11-24 3 29 26" src="https://user-images.githubusercontent.com/1074351/33216627-831daeec-d12c-11e7-9596-fbf30131d0f6.png">
<img width="1011" alt="2017-11-24 3 29 38" src="https://user-images.githubusercontent.com/1074351/33216626-82fe6b7c-d12c-11e7-9064-450dd406efdd.png">

**Comment by justinjjvanderhooft** [comment]
Looks good - I am assuming that the Peaklist Index column comes from the original MS1 csv file?

**Comment by ymcdull** [comment]
Yes, if there are some columns before "mass" in peaklist file, then assume it is users' index, and put it as 'Peaklist Index' in the table. If nothing before "mass", ignore this in the table.

**Comment by justinjjvanderhooft** [comment]
Two questions:
i) What if there are two columns before? Otherwise we should (re-)specify the required format on the website to indicate that unique identifiers should be in front of the mass.
ii) can't we copy the name of columns over? Or is that not so easy? Otherwise, we should point out that the unique identifiers will be called 'Peaklist index"....

**Comment by ymcdull** [comment]
i) Currently I just concatenate everything before "mass" as index. But yes, I think keep them as two columns would be better.
ii) Yes, copy the name of columns would be better, will do ;)

**Comment by justinjjvanderhooft** [comment]
re i) it is even essential if users want to use the values in those columns as unique identifiers to map to other tools/workflows :-)

re ii) cool!
