### ISSUE TITLE
Error in MGF with MS1-CSV loading

### ISSUE THREAD

**Issue by justinjjvanderhooft** [sdrogers/ms2ldaviz#122]
Loading the combination of this set of plant spectra (MGF format txt file) and MS1 csv file (csv format txt file - with intensities across 71 extracts) does throw the error mentioned below. Manually comparing m/z and RT values there seems to be a (very) good correlation so the matching should be straightforward....
There is a feature which is found once across the data set - that might be causing the conflict?
Could we try to debug this? :-)

----

Running lda on experiment_559 (Standard LDA to discover 300 Mass2Motifs in 71 plant extracts of Rhamnaceae - MS1 table provided - Q-ToF instrument - denoised spectra in MGF - minimum intensity on 50), K=300
CSV file = /home/django/ms2ldaviz/ms2ldaviz/media/experiment_559/171205_71extracts_MS1peaktable_MS2LDA.csv
mzML file = /home/django/ms2ldaviz/ms2ldaviz/media/experiment_559/METABOLOMICS-SNETS-e9e02c0b-downlo_4t89dlS.mgf
Loading peaks from /home/django/ms2ldaviz/ms2ldaviz/media/experiment_559/METABOLOMICS-SNETS-e9e02c0b-downlo_4t89dlS.mgf using peaklist /home/django/ms2ldaviz/ms2ldaviz/media/experiment_559/171205_71extracts_MS1peaktable_MS2LDA.csv
Filtering MS2 on intensity
21620 MS2 remaining
document_1
{'title': 'Scan Number: 1435', 'parentrt': 141.429993, 'mslevel': '2', 'filename': 'spec-00000.mgf', 'instrument': 'ion trap', 'charge': '1+', 'parentintensity': None, 'parentmass': 337.0928, 'scans': '1435'}
Traceback (most recent call last):
File "/home/django/ms2ldaviz/ms2ldaviz/uploads/tasks.py", line 70, in lda_task
corpus, metadata, word_mz_range = lda_load_mzml_and_make_documents(exp)
File "/home/django/ms2ldaviz/ms2ldaviz/uploads/lda_functions.py", line 42, in load_mzml_and_make_documents
ms1, ms2, metadata = loader.load_spectra([experiment.ms2_file.path])
File "../lda/code/ms2lda_feature_extraction.py", line 1258, in load_spectra
# add ms1, ms2 intensity filtering for msp input
File "../lda/code/ms2lda_feature_extraction.py", line 127, in process_peaklist
def process_peaklist(self, ms1, ms2, metadata):
File "../lda/code/ms2lda_feature_extraction.py", line 110, in _load_peak_list
featid = tokens_tuple[featid_index]
IndexError: list index out of range

----

[METABOLOMICS-SNETS-e9e02c0b-download_clustered_spectra-main.txt](https://github.com/sdrogers/ms2ldaviz/files/1576042/METABOLOMICS-SNETS-e9e02c0b-download_clustered_spectra-main.txt)
[171205_71extracts_MS1peaktable_MS2LDA.txt](https://github.com/sdrogers/ms2ldaviz/files/1576047/171205_71extracts_MS1peaktable_MS2LDA.txt)

**Comment by justinjjvanderhooft** [comment]
Update - just tried to run the MGF file alone and that seems to work okay! So it is  definitively something in the matching that goes wrong....

**Comment by ymcdull** [comment]
The reason is that in experiment 559, the separator in each line of peaklist file is ";", but the default separator in our code is ','. Each column cannot be extracted properly, which leads to "list index out of range" error. Will solve it soon.

**Comment by ymcdull** [comment]
@sdrogers A pull request submitted to LDA repo: https://github.com/sdrogers/lda/pull/24
