### ISSUE TITLE
Making MS2LDA analysis public for publication

### ISSUE THREAD

**Issue by justinjjvanderhooft** [sdrogers/ms2ldaviz#126]
Would it be possible (desirable) to make MS2LDA analysis public? i.e., the recent plant results are now part of a manuscript that is being written up - and it would be nice if https://ms2lda.org/basicviz/summary/566 would lead to the experimental results - without a need for registration. However, I would suggest to make it "view only" rather than edit.
What do you think?

**Comment by sdrogers** [comment]
Could be an option…would need to have a think about the best way to do it though…let me mull it over...
--
Dr. Simon Rogers
simon.d.rogers@gmail.com

**Comment by sdrogers** [comment]
Would you want to provide all the 'view' functionality?
One option would be to add a new category. At the moment, users can have 'edit' and 'view' rights on an experiment. But it could be that we also have 'public' which means that no login is required? Would require quite a few code changes though as a lot of the views use the `@login_required` decoration

**Comment by sdrogers** [comment]
But, in general, I think we should definitely try and make it work somehow.

**Comment by justinjjvanderhooft** [comment]
" But it could be that we also have 'public' which means that no login is required? Would require quite a few code changes though as a lot of the views use the @login_required decoration" --> how much? Is this doable?

**Comment by justinjjvanderhooft** [comment]
I think it is worth-while as we can then link to the experiments from papers - the experimental settings are also stored within the summary page so it makes is easy to share results.

**Comment by justinjjvanderhooft** [comment]
Perhaps good to think about this again? :-)

**Comment by joewandy** [comment]
Continued in issue #135
