### ISSUE TITLE
why did  my experiment not end up linked to a fs??

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/ms2ldaviz#131]

**Comment by justinjjvanderhooft** [comment]
What does fs mean??

**Comment by joewandy** [comment]
feature set?

**Comment by sdrogers** [comment]
fs...correct. I uploaded an experiment and it didn't have a featureset. Except it did. Maybe. Anyway, nothing for you guys to worry about!!

**Comment by sdrogers** [comment]
fixed
