### ISSUE TITLE
Defining the fragment ions binning window  for motif search.

### ISSUE THREAD

**Issue by lfnothias** [sdrogers/ms2ldaviz#133]
Hi guys,
It appears that this parameter cannot be changed in ms2lda.org web-server.
I am dealing with data acquired on Agilent Q-TOF. The calibration seems to have been poorly done, and it leads to mass that are not binned properly in the motifs (repetition of adjacent ions). Note that, in molecular networks, we used 0.05 Da window for the fragment ions, and it seems to cluster properly the related ions. Would it possible to add this feature to the web-server ? If not, I will just look into running the script locally. 
Thanks in advance,

**Comment by lfnothias** [comment]
Thanks a lot for the new feature 👍

**Comment by sdrogers** [comment]
You’re welcome! I haven’t been able to test it as thoroughly as I would have liked so please let me know how it works...
