### ISSUE TITLE
MotifDB - caching motifdb sets

### ISSUE THREAD

**Issue by justinjjvanderhooft** [sdrogers/ms2ldaviz#154]
Can we cache the url endpoint for the motifdb on our end rather than the caching at GNPS?
If not, a small proxy layer could be a solution but not preferable in view of maintenance.

**Comment by joewandy** [comment]
will look into caching stuff soon ..

**Comment by joewandy** [comment]
Done. The following 4 views are cached (in memory, using memcached).
```
    url(r'^list_motifsets/$',views.list_motifsets,name = 'list_motifsets'),
    url(r'^get_motifset/(?P<motifset_id>\w+)/$', views.get_motifset,name='get_motifset'),
    url(r'^get_motifset/$', views.get_motifset_post,name='get_motifset_post'),
    url(r'^get_motifset_metadata/(?P<motifset_id>\w+)/$', views.get_motifset_metadata,name='get_motifset_metadata'),
```
DEFAULT_CACHE_TIMEOUT used is 60 * 60 * 24
