### ISSUE TITLE
Correlate positive and negative mode alpha vectors

### ISSUE THREAD

**Issue by justinjjvanderhooft** [sdrogers/ms2ldaviz#24]
Not sure how to visualize it (?), but it would be a cool picture for the manuscript if we see any of the combinations that I passed on earlier showing up - and perhaps some novel ones?

**Comment by joewandy** [comment]
Justin said low priority, nice to have but maybe don't bother if no time.

**Comment by joewandy** [comment]
Whatever it is, seems like we're not doing it.
