### ISSUE TITLE
Integrate special matching codes (eg frank) into ms2ldavis somehow

### ISSUE THREAD

**Issue by joewandy** [sdrogers/ms2ldaviz#29]
Justin said this will greatly improve his productivity.

**Comment by sdrogers** [comment]
Do you mean spectral matching?
On the spectra, or the motifs, or both?

**Comment by joewandy** [comment]
Autocorrect.. Yes, I meant spectral matching, on the spectra and perhaps the motifs too. This will save the time that Justin has to spend on manual validation work. Not sure what the best approach is, what do you think? Easiest is to simply copy and paste the entire Frank codes and put them into ms2ldavis, but we end up with duplicates codes in pimp too.

**Comment by joewandy** [comment]
Impossible to do given the time.
