### ISSUE TITLE
Updated annotations are not shown in the tables of the multi_alphas page.

### ISSUE THREAD

**Issue by joewandy** [sdrogers/ms2ldaviz#32]
1. Update the annotation of any multi-file mass2motif
2. Go back to the multi_alphas page.
3. The newly updated annotation is not shown in the alpha & degree tables on that page .. because it still shows the old (cached) annotation value in mfe.alpha_matrix.

Probably have to change something at line 76 of views_lda_multi.py ..

**Comment by sdrogers** [comment]
It's not a bug. To make things faster, the alpha table is created and stored. This holds annotations. So when annotations are changed they don't appear until the cache is wiped. I couldn't find another way of making it tolerably non-slow...

**Comment by joewandy** [comment]
Yeah.. I saw that from the code now, but didn't realise this is the behaviour. Alternatively, we could store the alpha matrix but always pull the up-to-date annotation from the db? Mostly I was wondering why the annotation doesn't show up in the tables .. But as long as we're aware of that, it's fine.
