### ISSUE TITLE
Put multifile as a new app?

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/ms2ldaviz#34]
Might be neat to extract all the multifile stuff and make it into a new app?
What do you think @joewandy ?

**Comment by joewandy** [comment]
For the views, urls and templates etc, this should be straightforward, but for the models, it seems that their foreign keys will break when moved around to different apps ..? 

http://stackoverflow.com/questions/25648393/how-to-move-a-model-between-two-django-apps-django-1-7

This can still be done but will have to be careful about it ..

**Comment by sdrogers** [comment]
Yes, I thought about that. We don't actually need to move the models though. It would be neater if we did, but that might require more of a re-write than we want to do.

**Comment by joewandy** [comment]
Everything has been split into apps
