### ISSUE TITLE
ms2 filename not stored

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/ms2ldaviz#58]
The ms2_file field in the experiment object is empty after experiments have been run. Perhaps this is now removed once the file is deleted? I think the file should be deleted but the experiment should always remember the filename that was used to create it?

**Comment by sdrogers** [comment]
This isn't actually a problem. Must have been something that looked odd during testing.

**Comment by justinjjvanderhooft** [comment]
It is not a problem - but a user has no way to double check which file he/she has uploaded. I thought that was the background of the 'issue'. Could we copy the file name into the summary page?

**Comment by sdrogers** [comment]
I think it is there though, isn't it?
It's missing in some old ones because, I think, of things that happened during testing.
Next time you run a file with both an mzml and a peaklist, check in the summary. I think both will be there, if not we can investigate.

**Comment by justinjjvanderhooft** [comment]
It is there indeed! This is good as it could explain why results look odd/suspicious in case a wrong file was uploaded.
