### ISSUE TITLE
sklearn on deployed server

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/ms2ldaviz#6]
pip install sklearn doesn't work on deployed server. I've added some PCA stuff using this. Have made a branch `deploy_branch`, which doesn't have this stuff. Would be good to install the package so that we can have it on the deployed server...any ideas? Probably a linux thing??

**Comment by joewandy** [comment]
This is due to missing dependencies on the OS level, so scipy cannot be built, e.g. missing BLAS, the linear algebra library.. Fixed by installing the pre-built packages from ubuntu instead.

Just did a quick test, seems to work now.

    root@ms2ldaviz:~# python
    Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
    [GCC 4.8.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from sklearn import decomposition
    >>> quit()

**Comment by sdrogers** [comment]
Thanks! Case closed....
