### ISSUE TITLE
Additional computation at the end of the LDA task

### ISSUE THREAD

**Issue by joewandy** [sdrogers/ms2ldaviz#62]
We should also do the following computation at the end of the LDA task

1. Rate by conserved motifs
2. Overlap score

**Comment by sdrogers** [comment]
Point 1 is done on the fly (i.e. this information has no place to be stored)
Will do point 2 now...

**Comment by sdrogers** [comment]
Done...added to the end of the load_dict function

**Comment by justinjjvanderhooft** [comment]
So in model, the 'convervedness' cannot be stored as additional property of a Mass2Motif, i.e., like a degree, or variance in the Multifile analyses?

**Comment by sdrogers** [comment]
Correct. Degree isn't stored either. Variance is kind of stored, in a mucky way.
The reason coverdness and degree aren't is that they depend on thresholds, so as soon as the thresholds change, they are out of date.

**Comment by justinjjvanderhooft** [comment]
I see. That makes sense - i.e., these are not 'intrinsic' model properties.
