### ISSUE TITLE
Consistency in M2M_Doc threshold

### ISSUE THREAD

**Issue by justinjjvanderhooft** [sdrogers/ms2ldaviz#64]
The default doc_m2m_threshold	is 0.05 according to the global options, but it seems to be 0.01 in the newer experiment. In the network, 0.05 is prefilled and thus the degrees do not match within the motifs and the network. See snipit from one of the urineNGS016 motifs (loss of NH3)

![image](https://cloud.githubusercontent.com/assets/2318072/24697936/d96542fe-19e6-11e7-8a41-88b7ed8f0b46.png)

**Comment by justinjjvanderhooft** [comment]
adding an experiment option and setting the m2m_document threshold to 0.05 indeed changes the numbers:
![image](https://cloud.githubusercontent.com/assets/2318072/24698130/7b69da56-19e7-11e7-846c-b7e14bc70dc1.png)
So it seems like 0.01 is somehow the default value, whereas 0.05 is mentioned. I think we can go with 0.05.

**Comment by sdrogers** [comment]
Sounds like it's not picking up the global option. I can check that.

**Comment by sdrogers** [comment]
Ok, fixed. The problem was that if it couldn't find the option for the particular experiment it just randomly picked the first one it could find (maybe from another experiment). It now explicitly finds the global one. Note that this could cause crashes if the global options aren't set...
