### ISSUE TITLE
Link annotations not showing in the visualiser

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/ms2ldaviz#66]
Check viz code -- looks like it's not using the annotation attribute but crawling into the metadata. This stops linked annotations working.

**Comment by sdrogers** [comment]
Fixed...at the moment it uses the annotation although we could change this to the short annotation where it is available?

**Comment by justinjjvanderhooft** [comment]
Using the short name when available would be really useful as those are made for labelling (Figures, Tables, etc)
