### ISSUE TITLE
Document special nodes not changing colour

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/ms2ldaviz#7]
[maybe user error]
When I set special = True for a document node, its colour doesn't change. Whereas, for a topic, it does. Any ideas?

**Comment by joewandy** [comment]
I'm guessing user error? Saw nothing in the code that could lead to this. Both document and topic nodes are treated the same. I also did a quick test by setting all document nodes to special (in views.make_graph), and indeed they all turned red.

<img width="716" alt="screen shot 2016-07-25 at 23 20 28" src="https://cloud.githubusercontent.com/assets/2523391/17119591/c071014c-52be-11e6-9d6b-952cf196ce01.png">

**Comment by sdrogers** [comment]
Fair enough. User error it is!
