### ISSUE TITLE
Max size of post request

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/ms2ldaviz#78]
When using the API I was finding that there seemed to be a limit to the size of the POST request that I could send (500 spectra worked, more sometimes didn't). In theory, I think POST requests are limitless so it is a function of the web server.

This isn't necessarily a problem except if we want alpha values from the API (this is basically implemented but not fully integrated yet) in which case it is important that all spectra are decomposed at the same time (the alpha depends on the gamma values for all documents).

My guess is that there is an option set on the digital ocean web server that limits the size that we should try and increase....??

**Comment by joewandy** [comment]
might be a django setting

[1:51] 
DATA_UPLOAD_MAX_MEMORY_SIZE

[1:51] 
is a new setting in django 1.10

[1:52] 
default 2.5MB

joewandy [1:52 PM] 
ah

simon [1:52 PM] 
looks like the culprit

[1:52] 
what should I set it to?

joewandy [1:52 PM] 
+DATA_UPLOAD_MAX_MEMORY_SIZE
+---------------------------
+
+Default: ``2621440`` (i.e. 2.5 MB).
+
+The maximum size (in bytes) that a request body may contain before raising a
+``SuspiciousOperation`` error.

[1:53] 
you should get a SuspiciousOperation error if that’s exceeded

simon [1:53 PM] 
I get the following (in /var/log/upstart/gunicorn.log)

[1:53] 
RequestDataTooBig: Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.

joewandy [1:53 PM] 
yeah that must be it then

[1:54] 
‘You can set this to None to disable the check. Applications that are expected to receive unusually large form posts should tune this setting.’

simon [1:54 PM] 
the entire GNPS dataset is 4.9MB

[1:54] 
So, I might set to 10

[1:54] 
hard to imagine exceeding that
