### ISSUE TITLE
D3 switch between different methods for motif and document sizing and colouring

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/ms2ldaviz#82]
What it says in the title...

**Comment by joewandy** [comment]
Added a checkbox on the page to toggle whether to show MS1 analysis (or not) on the network. Does it do the job, or needs more options?

**Comment by joewandy** [comment]
TODO: make annotated motifs stand out more (bold the lines)

**Comment by joewandy** [comment]
Would be nice to load all the data at first and use javascript only to toggle between the different drawing of the network.
