### ISSUE TITLE
Compress json files

### ISSUE THREAD

**Issue by joewandy** [sdrogers/ms2ldaviz#9]
If we can enable json compression on the server, things will load faster.

https://www.digitalocean.com/community/tutorials/how-to-add-the-gzip-module-to-nginx-on-ubuntu-14-04

**Comment by joewandy** [comment]
Enabled in /etc/nginx/nginx.conf. Seems to be a bit faster.

**Comment by sdrogers** [comment]
Joe's on full NMR avoidance model.. I like it...

--
Dr Simon Rogers
Senior lecturer, School of Computing Science, University of Glasgow

**Comment by joewandy** [comment]
back to nmr now ...
