### ISSUE TITLE
MS1 matching bug?! Needs to be checked

### ISSUE THREAD

**Issue by justinjjvanderhooft** [sdrogers/ms2ldaviz#93]
Running lda on experiment_356 (Ecoli Anaerobically grown with ABX (continuous) pallet extractions - generated positive ionization mode fragmentation file - standard LDA to discover 300 Mass2Motifs - Q-Exactive pHILILC-MS/MS HCD stepped collision energy - PiMP MS1 peak list positive ionization mode provided), K=300
CSV file = /home/django/ms2ldaviz/ms2ldaviz/media/experiment_356/MS1_peaklist_Ecoli_ABX.csv
mzML file = /home/django/ms2ldaviz/ms2ldaviz/media/experiment_356/E_coli_Abx_An_with_Antibiotic_5Po_7iUDPz7.mzML
Loading peaks from /home/django/ms2ldaviz/ms2ldaviz/media/experiment_356/E_coli_Abx_An_with_Antibiotic_5Po_7iUDPz7.mzML using peaklist /home/django/ms2ldaviz/ms2ldaviz/media/experiment_356/MS1_peaklist_Ecoli_ABX.csv
Loading spectra from /home/django/ms2ldaviz/ms2ldaviz/media/experiment_356/E_coli_Abx_An_with_Antibiotic_5Po_7iUDPz7.mzML
Found 6569 ms2 spectra, and 149731 individual ms2 objects
Filtering MS1 on intensity
6505 MS1 remaining
149020 MS2 remaining
Filtering MS2 on intensity
65396 MS2 remaining
Loaded 2241 ms1 peaks from /home/django/ms2ldaviz/ms2ldaviz/media/experiment_356/MS1_peaklist_Ecoli_ABX.csv
0
Traceback (most recent call last):
File "/home/django/ms2ldaviz/ms2ldaviz/uploads/tasks.py", line 68, in lda_task
corpus, metadata, word_mz_range = lda_load_mzml_and_make_documents(exp)
File "/home/django/ms2ldaviz/ms2ldaviz/uploads/lda_functions.py", line 36, in load_mzml_and_make_documents
ms1, ms2, metadata = loader.load_spectra([experiment.ms2_file.path])
File "../lda/code/ms2lda_feature_extraction.py", line 371, in load_spectra
new_ms1 = MS1(old_ms1.id,peak_mz,peak_rt,peak_intensity,old_ms1.file_name,old_ms1.scan_number)
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by justinjjvanderhooft** [comment]
https://www.dropbox.com/sh/eh85hl6h91uubjo/AADTrXuEABKzp1XQoYCZq1HKa?dl=0
Link to input files used

**Comment by sdrogers** [comment]
I can also take a look tonight
