### ISSUE TITLE
Create a reviewer account

### ISSUE THREAD

**Issue by joewandy** [sdrogers/ms2ldaviz#97]
Feels better to me to create an account for the reviewer, rather than letting them use the guest account, where some functionalities aren't available under the guest account?

Also, should assign some sensible experiments for that account.

**Comment by justinjjvanderhooft** [comment]
Reviewer account was made (has the same functionalities as the guest account unless we grant it full access to the experimental options as well)

username: reviewer2017
password: motif123

The current experiments to look at are the same set as for the guest account, but one more decomposition experiment. Any other experiments that we are keen to show off? ;-)
